### ISSUE TITLE
Issue Tracker does not offer a full audit trail - is this a problem?

### ISSUE THREAD

**Issue by jastram** [openETCS/governance#107]
When discussing the product backlog within a WP7 meeting, @MarcBehrens was concerned about some tools (in this case waffle) not maintaining an audit trail on information (in this case the order if issues).

After thinking about this a little, I realized that this is a much broader issue: The gitHub issue tracker allows changing information (e.g. deleting comments, changing title and description), which **does not leave a single trace, whatsoever!**

We need WP1 to decide whether this is a problem, and if so, what to do about it.

**Comment by mahlmann** [comment]
As there is no quick solution to this issue, we have to keep working with the issue tracker as before. However, everyone should be  aware of this issue. I propose to close this issue for now. Feel free to re-open if you do not agree.
