### ISSUE TITLE
Alignment of WP7 Scrum Meetings

### ISSUE THREAD

**Issue by jastram** [openETCS/governance#109]
We have two weekly Scrum meetings, and the information about them is inconsistent.  Please align it.  There are three places that must match:

* The Scrum Wiki Page: https://github.com/openETCS/toolchain/wiki/Scrum-Weekly-Telco
* The admin@openETCS.org Calendar (this currently has the wrong info for Thursday)
* The gotoMeeting itself (The information text for the Thursday meeting states that it is supposed to start at 10:30, not 9:30).

Please also inform @cecilebraun , once this is fixed.

Thanks!

**Comment by mahlmann** [comment]
@Farhangi Please check if this has been fixed in the meantime.
